build frontend dockerfile and docker-compose

diff --git a/Dockerfile-frontend b/Dockerfile-frontend
--- a/Dockerfile-frontend
+++ b/Dockerfile-frontend
@@ -1,22 +1,55 @@
-# First stage: Build the binary
-FROM golang:1.20-buster AS builder
+# ref:
+#https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env
 
-LABEL stage=builder
+FROM node:16-alpine AS base
+
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+
+WORKDIR /base
+
+COPY ./frontend/package.json ./
+COPY ./frontend/package-lock.json* ./
+
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# 2. Rebuild the source code only when needed
+FROM base AS builder
 WORKDIR /build
 
-COPY frontend .
-RUN go mod download && CGO_ENABLED=0 go build -trimpath -o ./server ./backend/server.go
+COPY --from=deps /base/node_modules ./node_modules
+COPY ./frontend .
+COPY ./frontend/.env.production .env.production
+RUN yarn build
 
-# Second stage: Copy the binary from the builder stage and run it
-FROM alpine:latest
-
+# 3. Production image, copy all the files and run next
+FROM base AS runner
 WORKDIR /app
 
-COPY --from=builder /build/server .
-COPY ./backend/configs/container.yaml ./configs/container.yaml
+ENV NODE_ENV=production
 
-ENV WorkDir="/app"
-ENV ConfigPath="./configs/container.yaml"
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
 
-EXPOSE 8888
-CMD ["./server"]
+COPY --from=builder /build/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /build/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /build/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3001
+
+ENV PORT 3001
+
+CMD ["node", "server.js"]
